### ISSUE TITLE
Consider a slightly different CLI name?

### ISSUE THREAD

**Issue by spkane** [stuartleeks/devcontainer-cli#70]
This looks like an interesting alternative tool, but it might be good to choose a name that is at least slightly different from the official `devcontainer` CLI tool, just so people can easily use both if they provide any complimentary capabilities.

https://github.com/devcontainers/cli

**Comment by spkane** [comment]
No idea which came first, but it is a thought...

**Comment by stuartleeks** [comment]
Hi @spkane  - this CLI pre-dated devcontainers/cli but since it is an unofficial CLI I have been thinking about renaming it.

In fact, in my local install I don't have this project in my path and instead alias it as `devcontainerx`.

Did you have any alternate names in mind?

**Comment by spkane** [comment]
Makes sense. The name is so obvious that coming up with reasonable alternatives is a bit tricky.

Your alias is probably as good as any, although a change closer to the front would be nice for folks who tab complete the command name.

Here are a few random attempts at something...

-  development container
  - `devcontainerx`
  - `dcontainer`
  - `devc`
- workspace container
  - `wscontainer`
  - `wsc`
- visual studio code container (although I think the intent is for this to evolve into standard)
  - `vscontainer`

**Comment by stuartleeks** [comment]
How about dcx?

**Comment by spkane** [comment]
That works.

**Comment by stuartleeks** [comment]
Finally got round to this and I opted for `devcontainerx` in the end.

Note that the `update` command will fail unless you rename your existing binary `devcontainerx`
