### ISSUE TITLE
Discussion: Language Choice

### ISSUE THREAD

**Issue by CodeMan99** [stuartleeks/devcontainer-cli#81]
Hello!

I found this project after I started a similar project in Rust. My primary goal is to replace `devcontainer templates apply` from the official cli. So mostly just wanting to say hello! :smile:

I'd like to discuss the language choice. I really only chose Rust because I'm learning the language and because [clap-rs](https://docs.rs/clap/latest/clap/) is pretty awesome.

That said, I almost jumped ship to Go because of the [oras](https://github.com/oras-project/oras-go) library. That has been a pain point for me in Rust. I've forked the [ocipkg](https://github.com/CodeMan99/ocipkg/tree/feat/get-image-layer) project to accomplish pulling templates & features. My current implementation is sub-optimal as there is no cache usage 👎 

Another pain point is dealing with _JSON with comments_ that is used in devcontainer.json files. I'd like to be able to edit those files while keeping comments, but the well-supported [serde_json](https://github.com/serde-rs/json) library only really supports reading such files. Writing comments is pretty much out of the question.

P.S. I intend to publish my project to github later today. I'm not sold on the name I chose. 😬

**Comment by CodeMan99** [comment]
Published my tool: [devconf](https://github.com/CodeMan99/devconf). My README has a link to [this project](https://github.com/stuartleeks/devcontainer-cli). Would love some flavor text to include at the bullet 😅

**Comment by michidk** [comment]
I made [vscli](https://github.com/michidk/vscli) which is built in Rust and and uses a serde_json version that supports comments.
While it currently focuses on opening dev containers, I am open to add more functionality.

**Comment by CodeMan99** [comment]
> serde_json version that supports comments.

What do you mean by "supports"? Deserializing?

Ideally I'll like to be able to _uncomment_ a line like `    // "features": {}`, update that value while maintaining correct comma usage. Even using something like https://crates.io/crates/jsonc-parser is not all that straight forward.

---

> I am open to add more functionality.

We currently have pretty different goals. I'm intentionally not interacting with the editor or docker directly. I might be open to merging the two tools in the future... not sure.

---

Also, I renamed my project to `tyedev`. Feels much more unique now.

**Comment by stuartleeks** [comment]
@CodeMan99 I picked Go as it makes it easy to produce small, single-file binaries across multiple operating systems, and I'm comfortable writing it 😄

**Comment by CodeMan99** [comment]
> I'm comfortable writing it

That's totally fair!

I'd still like to improve my flavor text for the [link to your project](https://github.com/CodeMan99/tyedev#related-tools) (Related Tools). 🙏

**Comment by CodeMan99** [comment]
Found your entry on [awesome-devcontainers](https://github.com/manekinekko/awesome-devcontainers). Updated my flavor text from that.
